"""Regenerate src/main/kotlin/.../OpenCcTables.kt from the OpenCC dictionaries.

Usage (from the plugin module root):

    python tools/gen_opencc_tables.py

Source data: BYVoid/OpenCC (Apache-2.0), pinned to commit
3ac34aa439a9908dd49fa92b5174b46314787ac2. Dictionary files are read from
tools/ when present; otherwise they are downloaded from raw.githubusercontent
and their sha256 is verified against the pinned digests below.

Reduction applied (keeps the generated Kotlin small without losing behaviour):
  - char tables: keep the first candidate only, drop identity entries;
  - phrase tables: keep an entry only when converting its source
    character-by-character (with the char table) differs from the entry's
    target. This keeps both disambiguation entries (干杯 -> 乾杯) and
    anti-conversion identity entries (皇后 -> 皇后, where char-level would
    wrongly produce 皇後).
"""
import hashlib
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
MODULE = os.path.dirname(HERE)
OUT = os.path.join(
    MODULE, "src", "main", "kotlin", "com", "example", "hyperglow", "scriptconvert", "OpenCcTables.kt"
)

OPENCC_COMMIT = "3ac34aa439a9908dd49fa92b5174b46314787ac2"
BASE_URL = "https://raw.githubusercontent.com/BYVoid/OpenCC/%s/data/dictionary/" % OPENCC_COMMIT

# name -> sha256 of the pinned upstream file
FILES = {
    "STCharacters.txt": "a0ca1601c70648cf48b33c3c6210ccbecc5c7eead4b4c3daf76587ba2c03582b",
    "STPhrases.txt": "f6eab5e5c6dd7640597878d3dfc6599ee1279d2bc91561eadd8e114194e2925a",
    "TSCharacters.txt": "9ff46a7d30e5765375eb13d33f2b03a34d298913caf2b120380679f33ae1642d",
    "TSPhrases.txt": "9a23666e95c97dbf8668b5d71ca19f09f33b4f3a3aa9e05677dab4b608cef102",
}

CHUNK = 16000  # max chars per Kotlin string literal (class-file UTF-8 limit is 64 KiB)


def load_dictionary(name):
    local = os.path.join(HERE, name)
    if os.path.isfile(local):
        data = open(local, "rb").read()
    else:
        print("downloading", name)
        with urllib.request.urlopen(BASE_URL + name, timeout=60) as response:
            data = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != FILES[name]:
        sys.exit("sha256 mismatch for %s: %s" % (name, digest))
    return data.decode("utf-8")


def load_entries(text):
    entries = []
    for line in text.split("\n"):
        line = line.rstrip("\r")
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 2:
            continue
        targets = [t for t in parts[1].split(" ") if t]
        if targets:
            entries.append((parts[0], targets))
    return entries


def build_char_map(entries):
    m = {}
    for src, targets in entries:
        if len(src) != 1:
            continue
        target = targets[0]
        if target != src:
            m[src] = target
    return m


def charwise(text, char_map):
    return "".join(char_map.get(ch, ch) for ch in text)


def build_phrase_map(entries, char_map):
    m = {}
    for src, targets in entries:
        if len(src) < 2:
            continue
        target = targets[0]
        if charwise(src, char_map) == target:
            continue
        m[src] = target
    return m


def chunk_literal(text):
    out, cur, cur_len = [], [], 0
    for line in text.split("\n"):
        if cur and cur_len + len(line) + 1 > CHUNK:
            out.append("\n".join(cur))
            cur, cur_len = [], 0
        cur.append(line)
        cur_len += len(line) + 1
    if cur:
        out.append("\n".join(cur))
    return out


def kotlin_literal(s):
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "$":
            out.append("\\$")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def emit(mappings):
    parts = [
        "// Generated by tools/gen_opencc_tables.py — do not edit by hand.",
        "// Data: OpenCC dictionaries (https://github.com/BYVoid/OpenCC), Apache-2.0,",
        "// pinned at commit %s." % OPENCC_COMMIT,
        "// Format per line: <source>\\t<target>; entries are joined with '\\n'.",
        "package com.example.hyperglow.scriptconvert",
        "",
        "internal object OpenCcTables {",
    ]
    for const_name, mapping in mappings:
        lines = [k + "\t" + mapping[k] for k in sorted(mapping)]
        chunks = chunk_literal("\n".join(lines))
        parts.append("    private val %s_CHUNKS = arrayOf(" % const_name)
        for chunk in chunks:
            parts.append("        " + kotlin_literal(chunk) + ",")
        parts.append("    )")
        parts.append(
            '    val %s: String by lazy { %s_CHUNKS.joinToString("\\n") }' % (const_name, const_name)
        )
        parts.append("")
    parts.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts) + "\n")


def main():
    st_chars = build_char_map(load_entries(load_dictionary("STCharacters.txt")))
    st_phrases = build_phrase_map(load_entries(load_dictionary("STPhrases.txt")), st_chars)
    ts_chars = build_char_map(load_entries(load_dictionary("TSCharacters.txt")))
    ts_phrases = build_phrase_map(load_entries(load_dictionary("TSPhrases.txt")), ts_chars)
    print("s2t chars:", len(st_chars), "phrases:", len(st_phrases))
    print("t2s chars:", len(ts_chars), "phrases:", len(ts_phrases))
    emit([
        ("S2T_CHARS", st_chars),
        ("S2T_PHRASES", st_phrases),
        ("T2S_CHARS", ts_chars),
        ("T2S_PHRASES", ts_phrases),
    ])
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
